Add tool to convert TIPSY ICs to GENGA format
N-BodyShop/tipsy_tools pull request #4
Opened 2021-03-02 19:05 UTC by spencerw

2021-03-02 19:16 UTC, trquinn requested changes
Small changes requested.

2021-03-02 19:16 UTC, trquinn commented on bin2genga.c
> +	if(header.ndark != 0) {
It looks like you assume that nSph == 0 and nStar == 0.  You should check and assert on that.

2021-03-02 19:16 UTC, trquinn commented on bin2genga.c
> +    for(dp=dark_particles; dp< lastdp; dp++) {
Could you clean up the indentation?

2021-03-02 19:22 UTC, spencerw commented
Will do!

I'm also realizing that this tool doesn't seem to work with the ChaNGa output files (only the IC files that I create with ascii2bin). Is there another conversion that needs to be done to the ChaNGa outputs first? I've been using iBinaryOut = 0.

2021-03-02 19:57 UTC, spencerw commented
I see, let's leave "totipnat" to take care of that step and have this tool function similarly to "bin2ascii".

I realize I probably should have named this branch "bin2genga". I don't think there's a way to rename a branch after opening a pull request, so let me know if you want me to create a new one, or just merge as-is.

2021-03-02 20:41 UTC, closed without merging

2021-03-04 18:27 UTC, trquinn commented
This is superceded by pr #5